### ISSUE TITLE
-as, -is for import-psd? pattern-matching?

### ISSUE THREAD

**Issue by mazzy-ax** [nightroman/PsdKit#5]
Thanks for this module. It's smart.

The last test in the `StronglyTypedData.ps1` example make hard casting to `[Message[]]` type.
Is it possible to add some like `-as` or `-is` operators for `import-psd` function?

Yes, I am aware that `import-psd` works via `Import-LocalizedData` and `-is` need some typeinfo in psd-schema. 

Maybe you can use something like `pattern matching` due `import-psd`?

Thanks again.

**Comment by nightroman** [comment]
Casting does the trick. Why is the new parameter better that this? If we were importing data ourselves then  the parameter would be useful for better performance (perhaps). But you are right, we just use `Import-LocalizedData`, so the parameter will not add much value, we will continue converting the whole result by casting, only internally.

**Comment by mazzy-ax** [comment]
I'm agree that this checks may be the cause of performance issues. I'm agree, checks should not be mandatory.

It is possible that checking during the import can be implemented more optimally than checking after the import. So I was talking about the parameter. But it can be a separate function.

**Comment by nightroman** [comment]
After all, I do not think a parameter will make things more effective. The current batch conversion done by PowerShell casting is probably the fastest way. Maybe not memory efficient but the fastest for not huge data sets.

> Maybe you can use something like pattern matching due import-psd?

Can you please explain "pattern matching"?

**Comment by mazzy-ax** [comment]
ok. 

pattern matching:
https://en.wikipedia.org/wiki/Pattern_matching
https://docs.scala-lang.org/tour/pattern-matching.html
https://docs.microsoft.com/en-us/dotnet/csharp/pattern-matching

see also https://en.wikipedia.org/wiki/Duck_typing
if you want to consider a matching by hashtable keys

**Comment by nightroman** [comment]
Thank you... I still do not get what you are suggesting in the context of the module and `Import-Psd`.
Can you give some examples?

**Comment by mazzy-ax** [comment]
The context is the same as the context of operators `as`, `is`

**Comment by nightroman** [comment]
OK, I am closing this because in my opinion the feature is not needed in PsdKit.
