### ISSUE TITLE
add parameter -BindingVariable to import-psd?

### ISSUE THREAD

**Issue by mazzy-ax** [nightroman/PsdKit#7]
can you add parameter `-BindingVariable` to `import-psd` function?

The parameter will be useful if I want to add values from `psd1` to an existing variable.

Thanks for your module.

**Comment by nightroman** [comment]
Why is this needed, i.e. why cannot you add imported data to an existing variable yourself?

I am not saying it is not needed, just trying to understand. New features should not be added just because we can, even some useful features.

**Comment by mazzy-ax** [comment]
this is a typical approach for other languages: a file with default settings and a file with some settings that the administrator has configured. for example, [phpmyadmin](https://www.phpmyadmin.net/).

Yes, PowerShell does not yet have a generally accepted way to store configuration. See. for example, PSScriptAnalyzer.

But there is `Import-LocalizedData`, which allows you to add settings from a file to an existing [hastable]. So, we can to use 'default settings + some user settings' scenario with `Import-LocalizedData`.

I thought `PsdKit` would be perfect for storing settings and for serializing-deserializing, so I was looking for a way to implement this scenario.

**Comment by nightroman** [comment]
I see, it makes sense, especially because `Import-Psd` wraps `Import-LocalizedData` which has this parameter. It looks like we just need to add this parameter and pass it in `Import-LocalizedData`. Let me try and see how it goes.

**Comment by nightroman** [comment]
Instead of `-BindingVariable [string]` I am going to use `-Merge [hashtable]`. It effectively solves the task and works around notorious variable scope issues in script modules called from other scripts. I will release this after some testing.

Example:

```powershell
# existing data
$data = @{
    ...
}

# import and merge with existing
Import-Psd MyData.psd1 -Merge $data
```

**Comment by mazzy-ax** [comment]
I would suggest refining the name `-mergeInto` (or something in this style) to emphasize that the parameters from the psd1-file replaces the values in the variable.

A simple name `-merge` leaves the question: what value will remain after the merge?

**Comment by nightroman** [comment]
Yes, `-MergeInto` looks better.

**Comment by nightroman** [comment]
See v0.5.1, thank you for the useful suggestion.
